
const main = async () => {
  console.log('Hello world!')
}

main().catch(e => console.error(e))
